### ISSUE TITLE
Wall of Gratitude

### ISSUE THREAD

**Issue by vvwenv** [sitechtimes/PTA-Site#243]
- Be able to archive past donors/vendors and etc
- Thank donors
- Thank vendors

**Comment by DariaG16** [comment]
brainstorming

THE WALL:
- make an array from the CMS out of image, name, description maybe? 
- foreach the values in the array for the wall
THE ARCHIVE:
- make the arrays a larger array, name the arrays by the year, iterate through the larger arrays in the archive and make the foreach for the wall have variables that change the year
- title of the wall is the title of the larger array

smtg like that for now

**Comment by DariaG16** [comment]
when the cards are displayed, they should only display the cards corresponding to the year selected. 
ideas: 
the cards should be filtered through a variable (like "yr") which changes through a function when users click on different buttons.
The function for changing the year variable is already complete

all I need to do is find a way to filter through the array using a variable and foreach through that filter, with the filter changing every time the person changest the year.
