### ISSUE TITLE
gallery on home page distorted

### ISSUE THREAD

**Issue by vvwenv** [sitechtimes/PTA-Site#84]

**Comment by bridgetf7** [comment]
I cannot see the glitch when using the media queries so I'm not sure how to approach this issue/bug

**Comment by vvwenv** [comment]
The issue was not fixed.
Try to change the carousel to display only one photo on mobile screen sizes. 
Phone sizes are too small to display three photos.

**Comment by DariaG16** [comment]
Ok, I will also try to download a real phone emulator to help out

**Comment by DariaG16** [comment]
I didn't download it but I did change the amount of photos displayed to 1.5
can someone let me know if that fixes anything

**Comment by jessiey2** [comment]
will be fixed with new gallery
